kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: omsorgsopptjening-start-innlesning
  namespace: pensjonopptjening
  labels:
    team: pensjonopptjening
spec:
  kafka:
    pool: nav-dev
  azure:
    sidecar:
      enabled: true
      autoLogin: true
    application:
      enabled: true
      allowAllUsers: false
      claims:
        groups:
          - id: "7ef907b4-ec9f-47dd-ab41-4e54ba32ceb1" #AAD pensjonopptjening testgruppe
  gcp:
    sqlInstances:
      - type: POSTGRES_14
        cascadingDelete: true
        diskAutoresize: true
        pointInTimeRecovery: true
        name: omsorginnlesningdb
        tier: db-custom-1-3840
        databases:
          - name: omsorginnlesningdb
            envVarPrefix: DATABASE
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: dev-gcp
    - name: BARNETRYGD_URL
      value: http://omsorgsarbeid-ba-mock
#      value: http://teamfamilie.familie-ba-sak
  image: {{ image }}
  ingresses:
    - https://omsorgsopptjening-start-innlesning.intern.dev.nav.no
  accessPolicy:
    outbound:
      rules:
        - application: omsorgsarbeid-ba-mock
        - application: teamfamilie.familie-ba-sak
  liveness:
    path: /actuator/health/liveness
    port: 8080
    initialDelay: 50
  readiness:
    path: /actuator/health/readiness
    port: 8080
    initialDelay: 50
  prometheus:
    enabled: true
    path: /actuator/prometheus
  replicas:
    min: 1
    max: 1
  resources:
    limits:
      cpu: "2"
      memory: 4096Mi
    requests:
      cpu: 100m
      memory: 1024Mi