kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: omsorgsopptjening-start-innlesning
  namespace: pensjonopptjening
  labels:
    team: pensjonopptjening
spec:
  kafka:
    pool: nav-prod
  azure:
    sidecar:
      enabled: true
      autoLogin: true
    application:
      enabled: true
      allowAllUsers: false
      claims:
        groups:
          - id: "abd710c7-b01d-48e6-98b9-83ff615edf26" #AAD nais-team-pensjonopptjening
  secureLogs:
    enabled: true
  gcp:
    sqlInstances:
      - type: POSTGRES_16
        cascadingDelete: false
        diskAutoresize: true
        pointInTimeRecovery: true
        name: omsorginnlesning
        tier: db-custom-4-15360
        databases:
          - name: omsorginnlesning
            envVarPrefix: DATABASE
        flags:
          - name: cloudsql.enable_pgaudit
            value: on
          - name: pgaudit.log
            value: 'write'
  env:
    - name: PDL_URL
      value: https://pdl-api.prod-fss-pub.nais.io/graphql
    - name: PDL_API_ID
      value: prod-fss.pdl.pdl-api
    - name: SPRING_PROFILES_ACTIVE
      value: prod-gcp
    - name: BARNETRYGD_URL
      value: http://familie-ba-sak.teamfamilie
    - name: BARNETRYGD_API_ID
      value: prod-gcp.teamfamilie.familie-ba-sak
    - name: HJELPESTONAD_URL
      value: https://omsorgsopptjening-hjelpestonad-db-proxy.prod-fss-pub.nais.io
    - name: HJELPESTONAD_API_ID
      value: prod-fss.pensjonopptjening.omsorgsopptjening-hjelpestonad-db-proxy
    - name: OMSORGSOPPTJENING_TOPIC
      value: pensjonopptjening.omsorgsopptjening
    - name: BARNETRYGDMOTTAKERE_TOPIC
      value: teamfamilie.aapen-familie-ba-sak-identer-med-barnetrygd
    - name: BARNETRYGDMOTTAKERE_CONSUMER_GROUP
      value: omsorgsopptjening-start-innlesning
  envFrom:
    - secret: unleash-api-token
  image: {{ image }}
  ingresses:
    - https://omsorgsopptjening-start-innlesning.intern.nav.no
  accessPolicy:
    outbound:
      external:
        - host: omsorgsopptjening-hjelpestonad-db-proxy.prod-fss-pub.nais.io
        - host: pensjonopptjening-unleash-api.nav.cloud.nais.io
      rules:
        - application: familie-ba-sak
          namespace: teamfamilie
  liveness:
    path: /actuator/health/liveness
    port: 8080
    initialDelay: 50
  readiness:
    path: /actuator/health/readiness
    port: 8080
    initialDelay: 50
  prometheus:
    enabled: true
    port: "8080"
    path: /actuator/prometheus
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
  replicas:
    # satt til 0 for ikke å bruke ressurser mens det er idle, må skrus opp igjen til faktisk kjøring
    min: 1
    max: 1
  resources:
    limits:
      cpu: "2"
      memory: 4096Mi
    requests:
      cpu: 500m
      memory: 1024Mi