name: Bygg og deploy omsorgsopptjening-start-innlesning til dev-gcp

on:
  push:
    branches:
      - main
jobs:
  tag_build_and_deploy:
    name: 'Build, deploy and tag'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - name: 'Check available disk space on /tmp (1)'
        run: df -h /tmp

      - name: 'Remount larger /tmp'
        run: sudo mount -o remount,size=3G,noatime /tmp

      - name: 'Check available disk space on /tmp (2)'
        run: df -h /tmp

      # PULLER REPO
      - name: 'Pull repo'
        uses: actions/checkout@v4.1.1

      # SETTER DATO OG COMMIT VARIABEL
      - name: 'Setter dato og commit variabel'
        run: |
          export TZ=CET
          echo "DATE=$(date "+%Y-%m-%d--%H-%M-%S")" >> $GITHUB_ENV
          echo "COMMIT_HASH=$(git rev-parse HEAD)" >> $GITHUB_ENV
      # SETTER IMAGE VARIABEL
      - name: 'Setting Image Variabel'
        run: echo "IMAGE=docker.pkg.github.com/${{ github.repository }}/omsorgsopptjening-start-innlesning:${{ env.DATE }}---${{ env.COMMIT_HASH }}" >> $GITHUB_ENV

      # SETTER IMAGE GHCR VARIABEL
      - name: 'Setting Image ghcr Variabel'
        run: echo "IMAGE_GHCR=ghcr.io/${{ github.repository }}/omsorgsopptjening-start-innlesning:${{ env.DATE }}---${{ env.COMMIT_HASH }}" >> $GITHUB_ENV

      # JAVA 21
      - name: 'Java 21'
        uses: actions/setup-java@v4.0.0
        with:
          distribution: 'temurin'
          java-version: 21
          cache: 'gradle'

      # BYGGER DOCKER CONTAINER
      - name: 'Bygg og publiser docker image'
        run: |
          ./gradlew build
          docker build --tag ${{ env.IMAGE }} .
          docker login docker.pkg.github.com -u ${GITHUB_REPOSITORY} -p ${{ secrets.GITHUB_TOKEN }}
          docker push ${{ env.IMAGE }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: 'Check available disk space on /tmp after failure'
        if: failure()
        run: df -h /tmp

      # UPLOAD FAILED TEST RESULTS
      - name: 'Upload test results'
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-results-${{ matrix.runs-on }}
          path: build/reports/tests/test

      # DEPLOYER dev-gcp
      - name: 'Deploy omsorgsopptjening-start-innlesning to dev-gcp'
        uses: nais/deploy/actions/deploy@v2
        env:
          RESOURCE: nais/dev-gcp.yml,nais/unleash-apitoken-dev-gcp.yml
          CLUSTER: dev-gcp
          IMAGE: ${{ env.IMAGE_GHCR }}
