name: Bygg og deploy omsorgsopptjening-start-innlesning til prod-gcp

on:
  push:
    branches:
      - main
jobs:
  tag_build_and_deploy:
    name: 'Build, deploy and tag'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - name: 'Pull repo'
        uses: actions/checkout@v4.1.1

      - name: 'Setter dato og commit variabel'
        run: |
          export TZ=CET
          echo "DATE=$(date "+%Y-%m-%d--%H-%M-%S")" >> $GITHUB_ENV
          echo "COMMIT_HASH=$(git rev-parse HEAD)" >> $GITHUB_ENV

      - name: 'Java 21'
        uses: actions/setup-java@v4.0.0
        with:
          distribution: 'temurin'
          java-version: 21
          cache: 'gradle'

      - name: 'Build artifact'
        run: |
          ./gradlew build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: 'Build and push docker image'
        uses: nais/docker-build-push@v0
        id: docker-push
        with:
          team: pensjonopptjening
          tag: ${{ github.sha }}

      - name: 'Deploy omsorgsopptjening-start-innlesning to prod-gcp'
        uses: nais/deploy/actions/deploy@v2
        env:
          RESOURCE: nais/prod-gcp.yml,nais/unleash-apitoken-prod-gcp.yml
          CLUSTER: prod-gcp
          IMAGE: ${{ steps.docker-push.outputs.image }}
          TELEMETRY: ${{ steps.docker-push.outputs.telemetry }}